name: lyrics_app
description: "Lyrics App"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0 
  path: ^1.9.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: AccidentalPresidency
      fonts:
        - asset: assets/fonts/AccidentalPresidency.ttf

flutter_launcher_icons:
  android: true
  ios: false # если iOS не нужно
  image_path: "assets/icon/lyrics_icon.jpg"